apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ .Values.service.mongo.name }}
spec:
  selector:
    app: {{ .Values.service.mongo.app}}
  ports:
  - protocol: {{ .Values.service.mongo.protocol }}
    port: {{ .Values.service.mongo.port }}
    targetPort: {{ .Values.service.mongo.targetPort }}
  