apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.mongo.app }}-deployment
  labels:
    app: {{ .Values.service.mongo.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.mongo.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.service.mongo.app}}
    spec:
      containers:
        - name: {{ .Values.container.mongo.name }}
          image: {{ .Values.container.mongo.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.mongo.targetPort }}
          env:
            {{- include "funIterate" .Values.container.mongo.env | indent 12 }}



